### ISSUE TITLE
-> breaks the code formatting

### ISSUE THREAD

**Issue by lvl0nax** [Neodelf/lecter#10]
<img width="329" alt="Снимок экрана 2020-04-07 в 18 02 08" src="https://user-images.githubusercontent.com/1892604/78708277-c5e4e380-7909-11ea-8ba8-394173fb23f2.png">

`->` sign and numbers break the code formatting in the report

**Comment by Neodelf** [comment]
@lvl0nax thank you for your issue!
It was added because there are so many numbers before code. It leads to breaking indentation for some rows.
I have an idea to move sign `->` and numbers to the end of the line like
```
def create <- 1
  @post = Post.new(post_params) <- 2
...
```
But it maybe it leads to uncomfortable reading. What do you think?

**Comment by Neodelf** [comment]
It changed already. Documentation should be changed

**Comment by Neodelf** [comment]
It has fixed. Updated documentation is available in README

**Comment by Neodelf** [comment]
It has fixed. Updated documentation is available in README
