### ISSUE TITLE
Remove mount namespace from routes

### ISSUE THREAD

**Issue by Neodelf** [Neodelf/lecter#11]
According to documentation, we work with routes that start with `/lecter/diagnosis`. Its quite a long path, so I propose to remove `/diagnosis` part from routes. In the end, it will be only `/lecter` and we have routes like `/lecter/new`, `/lecter` and so on.

**Comment by pineapplethief** [comment]
Can I take this issue?

**Comment by Neodelf** [comment]
@pineapplethief Yes, sure!

**Comment by pineapplethief** [comment]
https://github.com/Neodelf/lecter/pull/40

**Comment by Neodelf** [comment]
Done in https://github.com/Neodelf/lecter/pull/40
