### ISSUE TITLE
Redirect from /lecter to /lecter/diagnosis/new

### ISSUE THREAD

**Issue by gambala** [Neodelf/lecter#50]
It's convenient to have such engines as /pghero, /sidekiq, /rails_performance, and /lecter, without need to remember additional /diagnosis/new subroute

**Comment by Neodelf** [comment]
It is a valuable suggestion. Do you want to use `/lecter/new`, and `/lecter` paths?

**Comment by gambala** [comment]
Just /lecter will be enough I think

**Comment by Neodelf** [comment]
It looks like an interesting improvement! 👍
